### ISSUE TITLE
add sphinx docs and move info from readme there

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#10]

**Comment by rbturnbull** [comment]
Hi @jjmccollum - I've refactored the docs and the readme a bit. I've merged the pull request myself because I wanted the docs to deploy to GH pages. You can see the update here: https://jjmccollum.github.io/teiphy/

I've also added a stub for the paper. it is converted to a PDF each push and it is deployed here: https://jjmccollum.github.io/teiphy/joss-draft.pdf

**Comment by jjmccollum** [comment]
Hey @rbturnbull! I just pulled the latest changes, and the updated documentation looks great! And thanks for the paper stub; I hope to get started on that soon! :smile:
