### ISSUE TITLE
testing coverage to 100%

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#28]
At the moment it is around 93%.

**Comment by jjmccollum** [comment]
All right, I've added some tests for `main.py` and have us up to 96% coverage. I'll probably turn to tests for `format.py`, `reading.py`, and `collation.py` next, as I'm not sure how to cover the highlighted code in `main.py` below:

![image](https://user-images.githubusercontent.com/15383366/188157392-076bb341-2452-45dc-88a9-c17c4e396490.png)

**Comment by jjmccollum** [comment]
Other than that, we should be at 99.83% coverage as of the latest push; the only uncovered line is the one above.

**Comment by rbturnbull** [comment]
Hi @jjmccollum - I took out that lines from main.py because it isn't needed anymore because we are using poetry to create the teiphy executable. Now the only statement that is untested is 144 in collation.py:

```
if rdg.type in self.missing_reading_types or len(rdg.targets) > 0 or len(rdg.certainties) > 0: 
               continue
```
There are no examples which get to the final part of the conditional `len(rdg.certainties) > 0`. Do you know a way of testing this? We need something were the rdg.type is not in missing_reading_types and len(rdg.targets) is zero.

**Comment by jjmccollum** [comment]
Thanks, @rbturnbull! Actually, based on the `Reading` class's `parse` method, the `certainties` dictionary should always be populated if the `targets` list is non-empty, and in some cases (e.g., if a `rdg` or `witDetail` has no `@target` attribute but has one or more `certainty` children), it may be populated even if the `targets` list is empty, so a better and less redundant check at this point in the code would be

```python
# If this reading is missing (e.g., lacunose or inapplicable due to an overlapping variant) or targets another reading, then skip it:
if rdg.type in self.missing_reading_types or len(rdg.certainties) > 0:
    continue
    
The check on `len(rdg.certainties)` was never being done because it was always first satisfied by the check on `len(rdg.targets)`. This updated version should give us full coverage. (At least that's what I'm seeing when I run `coverage report` with the updated code.)

So we may be all set to close this issue, if you think we're there. The only other thing that might need to be fixed is that the link on the coverage badge (which targets https://jjmccollum.github.io/teiphy/coverage/) still throws an Error 404.

**Comment by rbturnbull** [comment]
Hi @jjmccollum - i worked out the issue. I think a later version of coverage must add a .gitignore with a '*' which meant that the html report wasn't being committed to the gh-pages branch. I'm deleting that file now in the CI and the report is being deployed correctly. See it here: https://jjmccollum.github.io/teiphy/coverage/
