### ISSUE TITLE
adding help text for input and output in main.py

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#36]
I think there should be some help text for the input and output in the CLI. Also, is it OK if we call them just input and output - or perhaps input_path and output_path? I'm not sure if it is common to call them an `addr` for address.

**Comment by jjmccollum** [comment]
Yes, those arguments should be documented if they're not already. And I'm fine with their names being changed to `input` and `output`. I can go ahead and make these changes, unless you've already started.
