### ISSUE TITLE
CHARSTATELABELS block?

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#41]
I think some phylogenetics programs need the CHARSTATELABELS block filled out. (I thought BEAUTi needed it for example). Is it possible to include it. I've got an example here: https://github.com/rbturnbull/phylopaul/blob/main/1Corinthians/1Corinthians.nexus
I was lazy with that example and I just called the readings/states State0 or State1. It might be good to slugify the readings and have them in the states. I also include the site/character label in as a comment in square brackets. There should be a command line option to not have the CHARSTATELABELS block if the user doesn't want it. What do you think?

**Comment by jjmccollum** [comment]
This sounds good. The NEXUS paper actually recommends using CHARSTATELABELS in place of CHARLABELS (which we currently use) and STATELABELS (which we don't), so I can work on that. I'll have to add some attributes to the `Collation` class for storing and mapping these properly. And yeah, we can include a `--labels` command-line option (or, more appropriately, a `--no-labels` option if labels are included by default).

**Comment by rbturnbull** [comment]
awesome. It might be good to use a library like one of these to slugify the readings: 

- https://pypi.org/project/python-slugify/
- https://pypi.org/project/unicode-slugify/

**Comment by jjmccollum** [comment]
Will we want to change the unicode characters to ASCII if we're placing them in a NEXUS file?

**Comment by jjmccollum** [comment]
Okay, I've added support for this in the latest push to the `cicd` branch. I went with `python-slugify` for serializing the state labels. I'll plan to merge everything back into `main` once we have the other system tests incorporated into the CI pipeline.
