### ISSUE TITLE
logo/banner

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#44]
Hi @jjmccollum - it might be good to have a logo/banner. We can add a banner to the github repo so that the logo shows up when people share it on social media. Here's a draft banner which incorporates the TEI logo (https://tei-c.org/about/logos/). That logo is licensed under CC and it allows edits. The logo isn't pretty but it might be good to tie it in with TEI.

![teiphy-logo](https://user-images.githubusercontent.com/43091272/191516376-a00f156b-f8dd-4e6c-80e2-912b998ddcc4.png)

Are you happy with this or should we keep working on it

**Comment by jjmccollum** [comment]
@rbturnbull I think it looks great! The logo is simple, but elegant; like the software name, it combines the two ideas we want to bridge in a clear and uncomplicated way. I might consider using different fonts for the text portion of the logo; how do you feel about the following?

![image](https://user-images.githubusercontent.com/15383366/191532631-11f76c4a-f0c0-4435-9fef-04616997410f.png)

This uses 36pt Alegreya and 36pt Alegreya Sans Light for the title; the former is a humanist serif font that reflects the digital humanities side of TEI XML, and the latter is its companion sans-serif font, intended to capture the modern scientific and technological side of phylogenetics. Both fonts are available under the SIL Open Font License. I put the subtitle in dark gray 24pt Alegreya Sans Light for consistency.

**Comment by rbturnbull** [comment]
Hi @jjmccollum, I like the font. I originally just used Arial Black to match the existing TEI logo. How about this? The text is split up like the first one so that it fits within the aspect ratio (i.e. 1280x640).
![teiphy-logo2](https://user-images.githubusercontent.com/43091272/191626441-e9cf480c-6acb-4ae5-8eee-dba37374ea11.png)

**Comment by jjmccollum** [comment]
@rbturnbull This looks fantastic!  Feel free to add this to the readme (and anywhere else you think it should be added) and close the issue when you're ready. :smile:

**Comment by jjmccollum** [comment]
@rbturnbull Okay, I went ahead and added the following line to the top of `readme.rst`:

```rst
.. image:: https://github.com/jjmccollum/teiphy/blob/main/docs/img/teiphy-logo.png
```

And I uploaded the logo for the repo's social preview.

My only remaining question before we close this issue is, will the image link above work fine in PyPI, as well?

**Comment by jjmccollum** [comment]
@rbturnbull I think there's an issue with the SVG banner you uploaded in the latest push: for those who use dark mode in GitHub (like me), the transparency makes the logo significantly harder to read:

![image](https://user-images.githubusercontent.com/15383366/191713638-35cd3d99-13e5-4fa3-b8f1-efca012b56ec.png)

What should we do about that?

**Comment by rbturnbull** [comment]
Hi @jjmccollum - I've included a white background on the svg. I'm not sure if that's ideal but I don't know how to have a different image for dark or light modes. Can you please try it? You might need to go here and refresh: https://raw.githubusercontent.com/jjmccollum/teiphy/main/docs/img/teiphy-logo.svg because the image might be cached.

**Comment by jjmccollum** [comment]
@rbturnbull That looks better! I'll go ahead and close this issue. Before we submit the paper, I'll do a v0.1.1 release of the code so that the banner (not to mention all of our other recent changes) shows up on PyPI.

**Comment by rbturnbull** [comment]
good idea

**Comment by jjmccollum** [comment]
@rbturnbull I just made the v0.1.1 release on GitHub, but the `publish` action seems to be running into a problem. Here's the error log:

```
Publishing teiphy (0.1.0) to PyPI
 - Uploading teiphy-0.1.0-py3-none-any.whl 0%
 - Uploading teiphy-0.1.0-py3-none-any.whl 26%

 - Uploading teiphy-0.1.0-py3-none-any.whl 100%
HTTP Error 400: File already exists. See https://pypi.org/help/#file-name-reuse for more information. | b'<html>\n <head>\n  <title>400 File already exists. See https://pypi.org/help/#file-name-reuse for more information.\n \n <body>\n  <h1>400 File already exists. See https://pypi.org/help/#file-name-reuse for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nFile already exists. See https://pypi.org/help/#file-name-reuse for more information.\n\n\n \n'
Error: Process completed with exit code 1.
```

**Comment by rbturnbull** [comment]
Hi @jjmccollum - I think you need to bump the version number in the pyproject.toml. That's the version number that goes to PyPI. You might need to make it 0.1.2 and do a new release on GitHub for v0.1.2

**Comment by jjmccollum** [comment]
@rbturnbull Yeah, that's probably it. Sorry I forgot to change that!

**Comment by jjmccollum** [comment]
All right, it looks like we're all set! PyPI is now showing the v0.1.2 release with the banner!
