### ISSUE TITLE
Example in docs

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#45]
The last thing I think we need in the docs is a bit more info about how to use teiphy with different phylogenetics packages. I thought we could give examples from the Ephesians test XML file. I've written up stuff, taking info from the paper and the CI/CD. I'll commit it to a new branch in a moment.

**Comment by jjmccollum** [comment]
@rbturnbull It looks good! I've made some updates to account for some new features and pushed the latest changes. I'll go ahead and merge this into `main` next.
