### ISSUE TITLE
Add support for PHYLIP and FASTA formats

### ISSUE THREAD

**Issue by jjmccollum** [jjmccollum/teiphy#48]
Per the latest reviewer comments (https://github.com/openjournals/joss-reviews/issues/4879), support for PHYLIP and FASTA formats (used by programs like PHYLIP, RAxML, and IQTREE) would be convenient. Format parsing and output methods for these formats should be added to the code.

These changes can be made on the `code-revision` branch.

**Comment by jjmccollum** [comment]
Okay, I've added the code and unit tests (and fixed an error I made that was causing that last testing workflow to fail). If it's not too hard, it would be nice to add testing workflows with RAxML (https://github.com/stamatak/standard-RAxML), which can parse both PHYLIP and FASTA inputs, to ensure that the alignments we generate are valid. @rbturnbull, do you think it would be possible for us to clone the RAxML repo, do a build, and run RAxML with both types of input in a test runner?

**Comment by rbturnbull** [comment]
we can try it and build it and cache the result in github actions. Alternatively we can install it with conda: https://anaconda.org/bioconda/raxml

**Comment by jjmccollum** [comment]
Okay, I got a RAxML workflow that tests both PHYLIP and FASTA formats working on `code-revision`! I will now merge that branch into `main`.
