### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jjmccollum** [jjmccollum/teiphy#50]
Per the reviewer comments at https://github.com/openjournals/joss-reviews/issues/4879, we should add documentation on how to run the unit tests. From the GitHub repository, this is done via the command

```bash
poetry run pytest
```

@rbturnbull, is this all we need to add to the documentation, or is there some other way that we can run the unit tests if we've installed `teiphy` via pip?

**Comment by rbturnbull** [comment]
Hi @jjmccollum - sorry about the delay. I think you can only run the tests when you clone the repo. The tests aren't included in the python package

**Comment by jjmccollum** [comment]
@rbturnbull Thanks, I just wanted to clarify that point. In that case, what I've added to the readme should be sufficient. I'll close this issue now.
