### ISSUE TITLE
Add support for `--ascertainment` option

### ISSUE THREAD

**Issue by jjmccollum** [jjmccollum/teiphy#56]
Per the latest comments on https://github.com/openjournals/joss-reviews/issues/4879:
> The authors briefly mention how some phylogenetic software (like IQTree) can automatically perform ascertainment correction (usually with the Lewis MK model), but an `--ascertainment` flag would be very welcome for the NEXUS output format in general (or even for all formats). Not only some software expects the user to perform the correction themselves by adding the states to the alignment, but in some cases we might prefer to have it in the model even when the software offers it as an option.

I suspect that in NEXUS format, options like this would be specified in the ASSUMPTIONS block. If this specification is dependent on the target software (like IQ-TREE, MrBayes, or BEAST), the separate options may have to be developed for each software. I haven't yet found examples of NEXUS files that include these options.

These changes should be made on the `code-revision` branch.

**Comment by jjmccollum** [comment]
@rbturnbull If you're familiar with any of this, could I assign this issue to you?

**Comment by jjmccollum** [comment]
For IQ-TREE, the desired behavior is simple; if `--ascertainment` is not specified, then the command-line options for `iqtree` include `-m MK`; if it is specified, the options should include `-m MK+ASC`. The trick is handling this in the NEXUS output generated by `teiphy`. Is there a way to specify this in a block in the NEXUS file so that `iqtree` will read the options from that file?

For MrBayes, we conveniently have a MRBAYES block in the NEXUS file, so this approach to encoding the options in the input file is possible. Specifically, if `--ascertainment` is specified, then `lset coding=variable;` should be included in the MRBAYES block.

I'm hoping that there's a similar way to do this for BEAST2 using the ASSUMPTIONS block of the NEXUS file, since it already anticipates clock model calibration settings in the ASSUMPTIONS block.

**Comment by rbturnbull** [comment]
Hi @jjmccollum - sure, I'm happy to work on this one.

**Comment by jjmccollum** [comment]
@rbturnbull Now that you've added some discussion of this to the documentation, I'll go ahead and close this issue. If there are any outstanding issues related to this, feel free to reopen the issue.
