### ISSUE TITLE
add tip date sampling for beast

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#69]
See:
- http://www.beast2.org/features/miscellaneous-tip-date-sampling.html
- https://www.beast2.org/2015/06/09/sampling-tip-dates.html

**Comment by rbturnbull** [comment]
Hi @jjmccollum - this is now in the tipdates branch. It is running on my machine and in the CI. The date values seem to be changing in the log and are showing up in densitree.

**Comment by jjmccollum** [comment]
@rbturnbull Excellent! This will be a great feature to have in place for conversions from TEI to BEAST XML. If you have all the changes in place in that branch, feel free to make a pull request and I'll give it a look.

**Comment by rbturnbull** [comment]
Hi @jjmccollum - because it branched from the beast xml branch, it might be best to just merge it back to the beast branch and continue from there and then it can be merged with main through a PR when that is ready. If you're happy with that, should I merge it with the beast xml branch?

**Comment by jjmccollum** [comment]
@rbturnbull Oh, right. Yeah, a simple merge would be better in that case. Thanks for asking!

**Comment by rbturnbull** [comment]
I've merged tipdates into beast-xml. @jjmccollum you should be able to switch the templates to jinja now if you like
