### ISSUE TITLE
Relative path to chron file for stemma output

### ISSUE THREAD

**Issue by rbturnbull** [jjmccollum/teiphy#73]
Hi @jjmccollum  - at the moment the stemma chron file is given as an absolute path in the stemma output. Is it possible for this to be a relative path from the stemma file so that if you move the directories (or post them online) the paths can still work?

**Comment by jjmccollum** [comment]
@rbturnbull It looks like `collation.py` already imports `Path` from the `pathlib` module, so I'm sure it's possible to get the relative path using that.
